version: "3.9"

services:
  apache:
    build:
      context: .
    ports:
      - "8001:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - mysql

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=rob
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mysql

volumes:
  db-data:
networks:
  mysql:
    driver: bridge